name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build generator and definitions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: vendetta-mod/Vendetta
          path: vendetta

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install treetype-ts
        run: npm install --global treetype-ts

      - name: Generate defs
        run: |
          mkdir build
          ttgen -r @vendetta vendetta/src/def.d.ts VendettaObject build/defs.d.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sitereqs
          path: build

  publish:
    name: Publish the type definitions
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: sitereqs
          path: build

      - run: mv build/defs.d.ts npm_package
      - name: Publish package
        working-directory: npm_package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-site:
    name: Build the TypeDoc site
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i -g typescript typedoc

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sitereqs
          path: build

      - name: Build the documentation
        run: |
          mv build/defs.d.ts npm_package
          cd npm_package
          npm i
          cd ..

          echo '{"compilerOptions":{"target":"esnext","moduleResolution":"node","allowSyntheticDefaultImports":true,"skipLibCheck":true}}' > tsconfig.json

          typedoc npm_package/defs.d.ts

      - run: tar --directory docs -hcf artifact.tar .
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar

  # Deploy the above artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: build-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url  }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
